name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  tox:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            target: "py38"
          - python-version: "3.9"
            target: "py39"
          - python-version: "3.10"
            target: "py310"
          - python-version: "3.11"
            target: "py311"
          - python-version: "3.12"
            target: "py312"
          - python-version: "3.11"
            target: "pep8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install tox
          tox -e ${{ matrix.target }}
